Generated by Spark: This is whats happening in my terminal in codespaces
@avishashwat ➜ /workspaces/spark-template (main) $ sudo dockerd > /dev/null 2>&1 &
[1] 45861
@avishashwat ➜ /workspaces/spark-template (main) $ sleep 5
[1]+  Exit 1                  sudo dockerd > /dev/null 2>&1
@avishashwat ➜ /workspaces/spark-template (main) $ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
@avishashwat ➜ /workspaces/spark-template (main) $ sudo systemctl start docker

"systemd" is not running in this container due to its overhead.
Use the "service" command to start services instead. e.g.:

service --status-all
@avishashwat ➜ /workspaces/spark-template (main) $ service --status-all
 [ - ]  apparmor
 [ + ]  cgroupfs-mount
 [ - ]  dbus
 [ - ]  docker
 [ ? ]  hwclock.sh
 [ - ]  procps
 [ - ]  rsync
 [ + ]  ssh
 [ - ]  sudo
 [ + ]  supervisor
 [ - ]  x11-common
@avishashwat ➜ /workspaces/spark-template (main) $ sudo service docker start
mkdir: cannot create directory ‘cpuset’: Read-only file system